### ISSUE TITLE
Change of position setting leads to crash of Nextcloud setting page

### ISSUE THREAD

**Issue by moritz-h** [nextcloud/external#102]
### Steps to reproduce
1. Fresh Nextcloud Installation (from zip + use mysql)
2. Install External sites
3. Goto Settings -> External sites -> create example site
4. Switch Position setting multiple times to any of the three Settings until in the database table `oc_personal_settings` the entry `4 | OCA\External\Settings\Personal | personal-info | 55` is created.
(Seems to be some kind of race condition if the entry is created. Klicking 3-10 times was usually enough)
5. Switch position to Setting menu.
6. Try to open the settings page and see error.
(7. deleting the above mentioned table row fixes the problem temporarily. Can then try again from 4.)

### Expected behaviour
No Error

### Actual behaviour
Error

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache 2

**Database:** mysql

**PHP version:** 7.0

**Nextcloud version:** 13.0.2.1

**Where did you install Nextcloud from:** Zip from Homeapge

**List of activated apps:**

```
Only default ones + External sites
```

**Nextcloud configuration:**

```
default fresh installation
```

### Client configuration
**Browser:** Firefox

**Operating system:** Ubuntu 16.04

### Logs
```
{"reqId":"__ID__","level":3,"time":"__TIME__","remoteAddr":"127.0.0.1","user":"admin","app":"PHP","method":"GET","url":"\/__PATH__\/index.php\/settings\/user","message":"Undefined index: url at \/__PATH__\/apps\/external\/lib\/Settings\/Personal.php#58","userAgent":"__USERAGENT__","version":"13.0.2.1"}
{"reqId":"__ID__","level":3,"time":"__TIME__","remoteAddr":"127.0.0.1","user":"admin","app":"PHP","method":"GET","url":"\/__PATH__\/index.php\/settings\/user","message":"Undefined index: redirect at \/__PATH__\/apps\/external\/lib\/Settings\/Personal.php#59","userAgent":"__USERAGENT__","version":"13.0.2.1"}
{"reqId":"__ID__","level":3,"time":"__TIME__","remoteAddr":"127.0.0.1","user":"admin","app":"PHP","method":"GET","url":"\/__PATH__\/index.php\/settings\/user","message":"Undefined index: id at \/__PATH__\/apps\/external\/lib\/Settings\/Personal.php#60","userAgent":"__USERAGENT__","version":"13.0.2.1"}
{"reqId":"__ID__","level":3,"time":"__TIME__","remoteAddr":"127.0.0.1","user":"admin","app":"index","method":"GET","url":"\/__PATH__\/index.php\/settings\/user","message":"Exception: {\"Exception\":\"Symfony\\\\Component\\\\Routing\\\\Exception\\\\InvalidParameterException\",\"Message\":\"Parameter \\\"id\\\" for route \\\"external.site.showPage\\\" must match \\\"[^\\\/]++\\\" (\\\"\\\" given) to generate a corresponding URL.\",\"Code\":0,\"Trace\":\"#0 \\\/__PATH__\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php(136): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->doGenerate(Array, Array, Array, Array, Array, 'external.site.s...', 1, Array, Array)\\n#1 \\\/__PATH__\\\/lib\\\/private\\\/Route\\\/Router.php(337): Symfony\\\\Component\\\\Routing\\\\Generator\\\\UrlGenerator->generate('external.site.s...', Array, 1)\\n#2 \\\/__PATH__\\\/lib\\\/private\\\/URLGenerator.php(80): OC\\\\Route\\\\Router->generate('external.site.s...', Array)\\n#3 \\\/__PATH__\\\/apps\\\/external\\\/lib\\\/Settings\\\/Personal.php(60): OC\\\\URLGenerator->linkToRoute('external.site.s...', Array)\\n#4 \\\/__PATH__\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(115): OCA\\\\External\\\\Settings\\\\Personal->getForm()\\n#5 \\\/__PATH__\\\/settings\\\/Controller\\\/PersonalSettingsController.php(67): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->formatSettings(Array)\\n#6 \\\/__PATH__\\\/settings\\\/Controller\\\/CommonSettingsTrait.php(126): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->getSettings('personal-info')\\n#7 \\\/__PATH__\\\/settings\\\/Controller\\\/PersonalSettingsController.php(57): OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->getIndexResponse('personal', 'personal-info')\\n#8 [internal function]: OC\\\\Settings\\\\Controller\\\\PersonalSettingsController->index('personal-info')\\n#9 \\\/__PATH__\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#10 \\\/__PATH__\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Settings\\\\Controller\\\\PersonalSettingsController), 'index')\\n#11 \\\/__PATH__\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Settings\\\\Controller\\\\PersonalSettingsController), 'index')\\n#12 \\\/__PATH__\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Settings\\\\\\\\Con...', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#13 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#14 \\\/__PATH__\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#15 \\\/__PATH__\\\/lib\\\/base.php(999): OC\\\\Route\\\\Router->match('\\\/settings\\\/user')\\n#16 \\\/__PATH__\\\/index.php(37): OC::handleRequest()\\n#17 {main}\",\"File\":\"\\\/__PATH__\\\/3rdparty\\\/symfony\\\/routing\\\/Generator\\\/UrlGenerator.php\",\"Line\":163}","userAgent":"__USERAGENT__","version":"13.0.2.1"}
```

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
```

**Comment by moritz-h** [comment]
Same issue in #104.
Close as #104 is tagged bug and has more discussion.
